# Generated by Django 2.0.8 on 2019-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='signature',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
