# Generated by Django 2.0.8 on 2019-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_vote_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesubject',
            name='stater',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
